### ISSUE TITLE
Text symbology can not be edited

### ISSUE THREAD

**Issue by Zxcvbnm87** [ishiland/cmv-widgets#1]
Hi,

It appears there is a bug where the text symbology can not be edited. I'm unsure if this is intentional, but clicking Edit Symbol after right clicking on text will cause the edit popup window to appear which then can not be closed. As an immediate solution I have removed the edit symbol function from the right click menu to avoid my end users having to restart their maps.

**Comment by ishiland** [comment]
You are right, thanks for pointing this out. Its not something that is high priority for me right now but I will try and take a look next week. If you are able to come up with a more permanent fix in the meantime, feel free to submit a PR. Thanks.
