### ISSUE TITLE
How to add the angle for the rotation  in your super ADV Draw interface?

### ISSUE THREAD

**Issue by GilbertLasnier** [ishiland/cmv-widgets#2]
First thanks Ishiland to share your code with us... Its a great tools your Advance Draw
I go in advancedDrawConfig.js and I add the angle for the text, its work perfectly...
Do you know how to add that in your tool to be able to change the angle with a number, then I will be able to put the text parallel with my line or polygon, its will be super addin, also how to make a save file of or work int the Advance Draw??? 

},
        defaultTextSymbol: {
            color: [255, 0, 255, 255],
            type: 'esriTS',
			**angle:'40',**
            verticalAlignment: 'middle',
            horizontalAlignment: 'center',
            text: 'New Text',
            rotated: false,
            kerning: true,
            //haloSize: 12, // no esrijs support - try to make it work
            //haloColor: [255, 255, 255, 255], // no esrijs support - try to make it work
            //borderLineSize: 12, // no esrijs support - try to make it work
            //borderLineColor: [255, 0, 0, 255], // no esrijs support - try to make it work
            font: {
                size: 12,
                style: 'normal',
                variant: 'normal',
                weight: 'bold',
                family: 'sans-serif'
            }
        },
![image](https://user-images.githubusercontent.com/6784515/48493518-f9493e80-e7f9-11e8-94aa-bc015391d7c0.png)
Thanks again for you great work

**Comment by ishiland** [comment]
This should be doable. A simple input box could be added to the UI for specifying an angle. My thought is to add an angle input here:
![image](https://user-images.githubusercontent.com/3847952/48572839-95e20e00-e8d8-11e8-9b92-63550384d485.png)

It should be pretty straight forward but Ill take a look and see whats involved. If you make any progress or have other ideas please let me know.

**Comment by GilbertLasnier** [comment]
I try WHAT YOU TELL ME how to make a save file of or work in the Advance Draw???

**Comment by ishiland** [comment]
@GilbertLasnier what is your use case for saving the file? Do you want to be able to share with other users or simple persist the drawing between browser sessions? 

If the second is your case you can take a look at [writing to local storage](https://developers.arcgis.com/javascript/3/jssamples/exp_localstorage.html). 

I like the idea of using geojson for a saved drawing file but using the dojo `toJson` method may suit your needs. You will want to capture the SRID of the map whichever way you go.

**Comment by GilbertLasnier** [comment]
You are very fast, the idea its firs to don't lost the draw when we create something...
The second is good for me at that time, I believe 
If the second is your case you can take a look at writing to local storage.

I like the idea of using geojson for a saved drawing file but using the dojo toJson method may suit your needs. You will want to capture the SRID of the map whichever way you go.
there is an other advanced tool in the web app with the saving draw, maybe you are able to copy that part of the script...

**Comment by ishiland** [comment]
@GilbertLasnier I added the angle input option for Text. Please check it out and feel free to reopen this if you have any problems with it. I will open separate issue for saving drawings.

**Comment by GilbertLasnier** [comment]
Thanks to you to add the angle of the text, I try that this afternoon.
 I try also the advanced Draw from WEB APP from an other developer that you are able to save a json file but when i try to reload... its doesn't work, Also I try to add the JSON file in a Web App an other one i make with the functionality Add Data and also it doesn't work... so pay attention if you try to created the JSON file, it seem its a little bit hard to make a good one! 
Good luck and thanks again to be so fast, I love your Advanced tools.

**Comment by GilbertLasnier** [comment]
![image](https://user-images.githubusercontent.com/6784515/48916083-e0bad300-ee4e-11e8-9b46-411b795aed06.png)
I just copy the new files on my server two times I try, I check...and something is wrong?
Are you able to test if its working for you...ThankS
After i will be sure i am the problem!
Thanks again

**Comment by GilbertLasnier** [comment]
![image](https://user-images.githubusercontent.com/6784515/48916340-dcdb8080-ee4f-11e8-9098-730dfed9e483.png)
I just find that in the Console

**Comment by ishiland** [comment]
@GilbertLasnier I just cloned this repo and tried with the latest CMV, works OK for me. You can try and clear your browser cache to see if that helps. Otherwise I assume all the widget files are in the correct place?

**Comment by GilbertLasnier** [comment]
Thanks I try again this afternoon! Hope I succeed...
Thanks again, have a good day!

**Comment by GilbertLasnier** [comment]
I succed thanks again its work perfectly l like the arrows cool!
now somebody ask me to change the color of the text interactive , i change in the advancedDrawConfig.js
