### ISSUE TITLE
How to change the color of the text interactive in the widow Inteface? 

### ISSUE THREAD

**Issue by GilbertLasnier** [ishiland/cmv-widgets#4]
I don't know if its a great job but are we able to change the color of the text like you do with the other line polygon etc
![image](https://user-images.githubusercontent.com/6784515/48959781-b98b0100-ef35-11e8-9721-9bc79f157215.png)

**Comment by ishiland** [comment]
Yes this is related to #1 . Im working on a solution, hopefully will have something soon.

**Comment by ishiland** [comment]
@GilbertLasnier check out my most recent commit. I refactored the widget so the configuration file now lives in the usual CMV config directory. I also built a Text Editor that allows for more advanced text styling. 

I still need to work out a problem with editing the style of previously drawn text but I will open a separate issue for this.
