### ISSUE TITLE
Advanced Draw text editor not retaining text style on edit

### ISSUE THREAD

**Issue by ishiland** [ishiland/cmv-widgets#5]
On editing previously drawn text, the editor reverts the selected style and changes the opacity to 0, hiding the text. 

I suspect this has something to do with not being able to set the graphic text symbol [here](https://github.com/ishiland/cmv-widgets/blob/2efd0ca013ccbe8b3cfec54b9416dec652d354ee/AdvancedDraw/AdvancedDraw/widget/GraphicSymbolEditor.js#L114).

**Comment by GilbertLasnier** [comment]
Thanks for your great angle tools, its work perfectly!!
 when we are able to change the color of the text??
Thanks again...

**Comment by ishiland** [comment]
Hi - you should be able to edit all text properties, including color. The issue described here is that the text symbol editor resets all of the text properties and changes the transparency to 0.  

So you will notice the text disappear when you edit, but if you adjust the transparency you should see it again. From there all the properties should be editable. Hopefully Ill be able to revisit this issue soon and implement a fix.

**Comment by GilbertLasnier** [comment]
Thank for answer, I think i don't understand are we able to edit the Text
I try to put the transparencies to 1, still I have that screen , do you find on work around, by the way we work to try to make a save like in the: https://cmv.github.io/cmv-wab-widgets/demo.html?config=wab-measure
 but that one doesn't work when you try to reload the file nothing is drawing???
![image](https://user-images.githubusercontent.com/6784515/50009539-40575a80-ff85-11e8-9738-ce8edfd9f676.png)

**Comment by ishiland** [comment]
@GilbertLasnier try to clear your browser cache or open in incognito mode. 

The [demo](https://ishiland.github.io/cmv-widgets/) should exhibit the behavior i mentioned above.

**Comment by GilbertLasnier** [comment]
open in incognito mode, how to open in incognito mode, i dont know that!!
i try the demo now

**Comment by GilbertLasnier** [comment]
Great... Your demo work  perfectly maybe I don't have your latest version, now I must reload you latest version...what do you think? I don't have the same screen input for the text, they don't change its stay at polygon, take a look of the second screen, thank again...I will make a new version!!
![image](https://user-images.githubusercontent.com/6784515/50010318-13a44280-ff87-11e8-9743-71038d1a6bf3.png)
![image](https://user-images.githubusercontent.com/6784515/50010442-77c70680-ff87-11e8-825e-1eaeb8d42f39.png)

**Comment by ishiland** [comment]
This should now be resolved. Let me know if you still have any issues.
